openapi: 3.0.3
info:
  title: For ComboBox API
  description: ""
  version: 1.0.0
servers:
  - url: https://localhost/api
tags:
  - name: list and category
paths:
  /lists:
    get:
      tags:
        - list and category
      summary: Get All Lists API
      description: Get all lists by category and keyword
      parameters:
        - name: category
          in: path
          description: tab category
          required: false
          schema:
            type: string
        - name: keyword
          in: path
          description: input keyword
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lists"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /categories:
    get:
      tags:
        - list and category
      summary: Get All Categories API
      description: Get all tab categories
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

components:
  schemas:
    Lists:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: 営業本部
          category:
            type: string
            example: 部門
    Categories:
      type: array
      items:
      example:
        - 部門
        - 補助科目
